[tools]
aws-cli = { version = "latest", symlink_bins = "true" }
aws-sam-cli = { version = "latest", symlink_bins = "true" }
go = "latest"
zig = "latest"
bun = "latest"
argocd = "latest"
helm = "latest"
minikube = "latest"
k9s = "latest"
kubectl = "latest"
eksctl = "latest"
k6 = "latest"
istioctl = "latest"
krew = "latest"
kubectx = "latest"
kind = "latest"
jq = "latest"
bat = "latest"
yq = "latest"
ripgrep = "latest"
eza = "latest"
fzf = "latest"
tinymist = "latest"
gh = "latest"
duckdb = "latest"
typst = "latest"
chezmoi = "latest"
act = "latest"
terraform = "latest"
uv = "latest"
node = "22.14.0"
just = "latest"
